/**
 * Mock WorkflowRun fixtures used by the Inspector UI in V1.
 *
 * These are the "ideal" V1 shapes — they assume the V2 harness extension
 * (per-step prompts, timing, usage) is in place. The Inspector renders
 * whatever fields are present and falls back to "Data not captured in V1"
 * for the rest. Real `RunArtifact`-driven data in V1 will look sparser.
 */

import type { WorkflowRun } from '../../../shader-agent/integration/workflow-types';

const NOW = 1_700_000_000_000;

function makeSuccessRun(): WorkflowRun {
  const t0 = NOW;
  return {
    id: 'run-mock-success',
    createdAt: t0,
    finishedAt: t0 + 12_400,
    totalDurationMs: 12_400,
    userPrompt: 'a black hole with violet accretion disk, gravitational lensing, drifting star dust',
    workflow: 'generate',
    status: 'success',
    currentStage: 'screenshot_renderer',
    steps: [
      {
        kind: 'visual_structurer',
        index: 0,
        title: 'Visual Structurer',
        status: 'success',
        startedAt: t0,
        endedAt: t0 + 600,
        durationMs: 600,
        provider: 'openai',
        model: 'gpt-4o-mini',
        usage: { promptTokens: 412, completionTokens: 218, totalTokens: 630 },
        systemPrompt: 'You are a shader intent parser. Output a JSON object matching the ShaderSpec schema exactly. Allowed fields: intent, scene, material, style, motion, depth, lighting, color, interaction, constraints.',
        userPromptSent: 'a black hole with violet accretion disk, gravitational lensing, drifting star dust',
        rawLlmResponse: '{"intent":"create","scene":{"type":"cosmic","composition":"center_focus"},"material":{"type":"nebula_gas"},"style":{"mood":"cosmic"},"motion":{"type":"swirl","camera":"orbit"},"depth":{"approach":"volumetric"},"lighting":{"model":"emissive"},"color":{"palette":"purple_blue"},"interaction":{"type":"mouse_reactive"},"constraints":{"target":"webgl2","performance":"desktop_balanced","maxIterations":48,"allowRaymarching":true,"allowTextures":false}}',
        output: {
          intent: 'create',
          scene: { type: 'cosmic', composition: 'center_focus' },
          material: { type: 'nebula_gas' },
          style: { mood: 'cosmic' },
          motion: { type: 'swirl', camera: 'orbit' },
          depth: { approach: 'volumetric' },
          lighting: { model: 'emissive' },
          color: { palette: 'purple_blue' },
        },
        notes: 'Parsed cosmic + center_focus from prompt.',
      },
      {
        kind: 'shader_planner',
        index: 1,
        title: 'Shader Planner',
        status: 'success',
        startedAt: t0 + 600,
        endedAt: t0 + 700,
        durationMs: 100,
        output: {
          baseTechnique: 'sdf',
          coordinateSystem: 'polar',
          noise: 'fbm',
          motion: 'swirl',
          colorMethod: 'palette_function',
          effects: ['glow', 'fog'],
          composition: 'centered',
          performance: 'desktop_balanced',
          maxLoopBudget: 48,
          avoid: [],
          promptHints: ['use radial sampling', 'add volumetric falloff'],
        },
        notes: 'Deterministic — no LLM call.',
      },
      {
        kind: 'reference_selector',
        index: 2,
        title: 'Reference Selector',
        status: 'success',
        startedAt: t0 + 700,
        endedAt: t0 + 750,
        durationMs: 50,
        output: [
          { id: 'cosmic-polar', title: 'Cosmic Polar Field', kind: 'golden', tags: ['cosmic', 'polar'] },
          { id: 'volumetric-fog', title: 'Volumetric Fog', kind: 'golden', tags: ['volumetric', 'fog'] },
        ],
        notes: '2 of 9 golden shaders selected.',
      },
      {
        kind: 'code_agent_generate',
        index: 3,
        title: 'Code Agent (Generate)',
        status: 'success',
        startedAt: t0 + 750,
        endedAt: t0 + 3_200,
        durationMs: 2_450,
        provider: 'openai',
        model: 'gpt-4o-mini',
        usage: { promptTokens: 1_820, completionTokens: 612, totalTokens: 2_432 },
        systemPrompt: 'You are an expert GLSL shader author. Output Shadertoy-compatible mainImage(). Use the provided VisualCard and ShaderPlan to construct the code. Wrap your final GLSL in a fenced code block.',
        userPromptSent: 'VisualCard: { ... } ShaderPlan: { ... } References: [...] User prompt: "a black hole with violet accretion disk..."',
        rawLlmResponse: '```glsl\nvoid mainImage(out vec4 fragColor, in vec2 fragCoord) {\n  vec2 uv = (fragCoord - 0.5*iResolution.xy) / iResolution.y;\n  // ... ~80 lines of GLSL ...\n}\n```',
        output: 'void mainImage(out vec4 fragColor, in vec2 fragCoord) { /* ... */ }',
        notes: 'Generated ~80 lines of GLSL.',
      },
      {
        kind: 'shader_compiler',
        index: 4,
        title: 'Compile',
        status: 'success',
        startedAt: t0 + 3_200,
        endedAt: t0 + 3_300,
        durationMs: 100,
        output: { ok: true, errors: [], rawLog: '', durationMs: 95 },
        notes: 'Compiled on first attempt.',
      },
      {
        kind: 'screenshot_renderer',
        index: 5,
        title: 'Screenshot Renderer',
        status: 'success',
        startedAt: t0 + 3_300,
        endedAt: t0 + 3_900,
        durationMs: 600,
        output: { frameCount: 5 },
        notes: '5 frames @ 256x256. Visual score 78/100.',
      },
    ],
    finalCode: 'void mainImage(out vec4 fragColor, in vec2 fragCoord) { /* ... */ }',
    visualScore: 78,
    visualBreakdown: {
      color: { score: 82, reason: 'Palette is on-target.' },
      brightness: { score: 75, reason: 'Slightly dim in the lower half.' },
      contrast: { score: 80, reason: 'Strong center-to-edge contrast.' },
      motion: { score: 76, reason: 'Camera orbit is smooth but slow.' },
    },
  };
}

function makeFixRetryRun(): WorkflowRun {
  const t0 = NOW - 60_000;
  return {
    id: 'run-mock-fix-retry',
    createdAt: t0,
    finishedAt: t0 + 18_900,
    totalDurationMs: 18_900,
    userPrompt: 'a violet aurora over a frozen lake, mirror reflection, slow drift',
    workflow: 'generate',
    status: 'success',
    currentStage: 'screenshot_renderer',
    steps: [
      {
        kind: 'visual_structurer',
        index: 0,
        title: 'Visual Structurer',
        status: 'success',
        startedAt: t0,
        endedAt: t0 + 700,
        durationMs: 700,
        provider: 'openai',
        model: 'gpt-4o-mini',
        usage: { promptTokens: 420, completionTokens: 240, totalTokens: 660 },
        output: {
          intent: 'create',
          scene: { type: 'aurora', composition: 'layered_depth' },
          material: { type: 'light' },
          style: { mood: 'ethereal' },
          motion: { type: 'drift', camera: 'static' },
          depth: { approach: 'layered' },
          lighting: { model: 'emissive' },
          color: { palette: 'purple_blue' },
        },
        notes: 'Parsed aurora + layered_depth from prompt.',
      },
      {
        kind: 'shader_planner',
        index: 1,
        title: 'Shader Planner',
        status: 'success',
        startedAt: t0 + 700,
        endedAt: t0 + 800,
        durationMs: 100,
        output: { baseTechnique: 'domain_warp', coordinateSystem: 'cartesian' },
        notes: 'Deterministic — no LLM call.',
      },
      {
        kind: 'reference_selector',
        index: 2,
        title: 'Reference Selector',
        status: 'success',
        startedAt: t0 + 800,
        endedAt: t0 + 850,
        durationMs: 50,
        output: [
          { id: 'aurora-ribbon', title: 'Aurora Ribbon', kind: 'golden', tags: ['aurora'] },
        ],
        notes: '1 of 9 golden shaders selected.',
      },
      {
        kind: 'code_agent_generate',
        index: 3,
        title: 'Code Agent (Generate)',
        status: 'success',
        startedAt: t0 + 850,
        endedAt: t0 + 3_400,
        durationMs: 2_550,
        provider: 'openai',
        model: 'gpt-4o-mini',
        usage: { promptTokens: 1_900, completionTokens: 480, totalTokens: 2_380 },
        notes: 'First-pass code (with bug — fixed in next iteration).',
      },
      {
        kind: 'shader_compiler',
        index: 4,
        title: 'Compile #1',
        status: 'error',
        startedAt: t0 + 3_400,
        endedAt: t0 + 3_500,
        durationMs: 100,
        output: {
          ok: false,
          errors: [
            { line: 42, column: 9, message: "Use of undeclared identifier 'iPolar'", category: 'undeclared' },
          ],
          rawLog: 'ERROR: 0:42: Use of undeclared identifier \'iPolar\'\n',
          durationMs: 92,
        },
        error: { message: "L42: Use of undeclared identifier 'iPolar'" },
        notes: 'Compile failed: 1 error.',
      },
      {
        kind: 'code_agent_fix_compile',
        index: 5,
        title: 'Code Agent (Fix Compile) #1',
        status: 'success',
        startedAt: t0 + 3_500,
        endedAt: t0 + 6_800,
        durationMs: 3_300,
        provider: 'openai',
        model: 'gpt-4o-mini',
        usage: { promptTokens: 2_400, completionTokens: 510, totalTokens: 2_910 },
        systemPrompt: 'You are fixing a GLSL shader. The previous compile failed. Apply the minimal fix. Wrap your final GLSL in a fenced code block.',
        userPromptSent: 'Previous code: ... Previous errors: L42: Use of undeclared identifier \'iPolar\'',
        notes: 'Fix retry — replaced iPolar with computed polar coordinates.',
      },
      {
        kind: 'shader_compiler',
        index: 6,
        title: 'Compile #2',
        status: 'success',
        startedAt: t0 + 6_800,
        endedAt: t0 + 6_900,
        durationMs: 100,
        output: { ok: true, errors: [], rawLog: '', durationMs: 88 },
        notes: 'Compiled on second attempt.',
      },
      {
        kind: 'screenshot_renderer',
        index: 7,
        title: 'Screenshot Renderer',
        status: 'success',
        startedAt: t0 + 6_900,
        endedAt: t0 + 7_500,
        durationMs: 600,
        output: { frameCount: 5 },
        notes: '5 frames @ 256x256. Visual score 84/100.',
      },
    ],
    finalCode: 'void mainImage(out vec4 fragColor, in vec2 fragCoord) { /* fixed version */ }',
    visualScore: 84,
  };
}

function makeFailedRun(): WorkflowRun {
  const t0 = NOW - 120_000;
  return {
    id: 'run-mock-failed',
    createdAt: t0,
    finishedAt: t0 + 9_400,
    totalDurationMs: 9_400,
    userPrompt: 'a photorealistic ocean with caustics, refraction, foam, and accurate dispersion',
    workflow: 'generate',
    status: 'failed',
    steps: [
      {
        kind: 'visual_structurer',
        index: 0,
        title: 'Visual Structurer',
        status: 'success',
        startedAt: t0,
        endedAt: t0 + 600,
        durationMs: 600,
        output: { intent: 'create', scene: { type: 'ocean' }, constraints: { maxIterations: 64 } },
        notes: 'Parsed ocean scene.',
      },
      {
        kind: 'shader_planner',
        index: 1,
        title: 'Shader Planner',
        status: 'success',
        durationMs: 100,
        notes: 'Deterministic — no LLM call.',
      },
      {
        kind: 'reference_selector',
        index: 2,
        title: 'Reference Selector',
        status: 'success',
        durationMs: 50,
        output: [{ id: 'water-ripple', title: 'Water Ripple', kind: 'golden', tags: ['liquid'] }],
        notes: '1 of 9 selected.',
      },
      {
        kind: 'code_agent_generate',
        index: 3,
        title: 'Code Agent (Generate)',
        status: 'error',
        startedAt: t0 + 750,
        endedAt: t0 + 2_300,
        durationMs: 1_550,
        provider: 'openai',
        model: 'gpt-4o-mini',
        error: { message: 'LLM response did not contain a valid GLSL code block after 3 parse retries.' },
        notes: 'Code Agent could not extract a parseable mainImage() from LLM response.',
      },
      {
        kind: 'shader_compiler',
        index: 4,
        title: 'Compile #1',
        status: 'error',
        startedAt: t0 + 2_300,
        endedAt: t0 + 2_400,
        durationMs: 100,
        output: { ok: false, errors: [{ line: 1, message: "Expected 'void' before 'mainImage'", category: 'syntax' }], rawLog: '', durationMs: 90 },
        error: { message: "L1: Expected 'void' before 'mainImage'" },
        notes: 'Compile failed.',
      },
      {
        kind: 'code_agent_fix_compile',
        index: 5,
        title: 'Code Agent (Fix Compile) #1',
        status: 'error',
        startedAt: t0 + 2_400,
        endedAt: t0 + 5_300,
        durationMs: 2_900,
        error: { message: 'LLM fix-retry produced unparseable output.' },
        notes: 'Fix retry failed at the parser.',
      },
      {
        kind: 'shader_compiler',
        index: 6,
        title: 'Compile #2',
        status: 'error',
        durationMs: 100,
        output: { ok: false, errors: [{ line: 1, message: 'Truncated GLSL', category: 'syntax' }], rawLog: '', durationMs: 90 },
        error: { message: 'L1: Truncated GLSL' },
        notes: 'Compile failed.',
      },
      {
        kind: 'code_agent_fix_compile',
        index: 7,
        title: 'Code Agent (Fix Compile) #2',
        status: 'error',
        startedAt: t0 + 5_400,
        endedAt: t0 + 8_900,
        durationMs: 3_500,
        error: { message: 'LLM fix-retry produced unparseable output.' },
        notes: 'Fix retry failed again.',
      },
      {
        kind: 'shader_compiler',
        index: 8,
        title: 'Compile #3',
        status: 'error',
        durationMs: 100,
        output: { ok: false, errors: [{ line: 1, message: 'Truncated GLSL', category: 'syntax' }], rawLog: '', durationMs: 95 },
        error: { message: 'L1: Truncated GLSL' },
        notes: 'Compile failed. Max attempts reached.',
        warnings: ['Max compile attempts (3) reached.'],
      },
    ],
    visualScore: undefined,
  };
}

function makeRunningRun(): WorkflowRun {
  const t0 = NOW - 2_000;
  return {
    id: 'run-mock-running',
    createdAt: t0,
    totalDurationMs: undefined,
    userPrompt: 'a geometric mandala pulsing with cyan and magenta',
    workflow: 'generate',
    status: 'running',
    currentStage: 'code_agent_generate',
    steps: [
      {
        kind: 'visual_structurer',
        index: 0,
        title: 'Visual Structurer',
        status: 'success',
        startedAt: t0,
        endedAt: t0 + 500,
        durationMs: 500,
        output: { intent: 'create', scene: { type: 'mandala' } },
        notes: 'Done.',
      },
      {
        kind: 'shader_planner',
        index: 1,
        title: 'Shader Planner',
        status: 'success',
        durationMs: 80,
        notes: 'Done.',
      },
      {
        kind: 'reference_selector',
        index: 2,
        title: 'Reference Selector',
        status: 'success',
        durationMs: 40,
        output: [{ id: 'mandala', title: 'Mandala', kind: 'golden', tags: ['mandala'] }],
        notes: 'Done.',
      },
      {
        kind: 'code_agent_generate',
        index: 3,
        title: 'Code Agent (Generate)',
        status: 'running',
        startedAt: t0 + 1_400,
        notes: 'Awaiting LLM response...',
      },
      {
        kind: 'shader_compiler',
        index: 4,
        title: 'Compile',
        status: 'pending',
        notes: 'Waiting for Code Agent...',
      },
      {
        kind: 'screenshot_renderer',
        index: 5,
        title: 'Screenshot Renderer',
        status: 'pending',
        notes: 'Waiting for Compile...',
      },
    ],
  };
}

export const MOCK_RUN_SUCCESS = makeSuccessRun();
export const MOCK_RUN_WITH_FIX_RETRY = makeFixRetryRun();
export const MOCK_RUN_FAILED = makeFailedRun();
export const MOCK_RUN_RUNNING = makeRunningRun();

export const MOCK_RUN_EMPTY: WorkflowRun = {
  id: 'run-empty',
  createdAt: 0,
  userPrompt: '',
  workflow: 'generate',
  status: 'idle',
  steps: [],
};
